spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:order-delivery;MODE=MySQL;
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true