@startuml

' deliveryapp.deliveryStarted() -> orderapp.deliveryStarted()
' deliveryapp.deliveryCompleted() -> orderapp.deliveryCompleted()
' paymentapp.approvePayment() -> orderapp.paymentApproved()
' paymentapp.rejectPayment -> orderapp.orderCancelled() ???

state orderapp {
    [*] --> PLACED: placeOrder()
    PLACED --> PAYMENT_APPROVED: approvePayment()
    PAYMENT_APPROVED --> DELIVERY_STARTED: startDelivery()
    DELIVERY_STARTED --> DELIVERY_COMPLETED: completeDelivery()
    DELIVERY_COMPLETED --> [*]
    PLACED --> CANCELLED: cancelOrder()
    PAYMENT_APPROVED --> CANCELLED: cancelOrder()
    CANCELLED --> [*] 
}

state deliveryapp {
    ' CANCELLED ???
    [*] --> SUBMITTED: createDelivery()
    SUBMITTED --> STARTERD: startDelivery()
    STARTERD --> COMPLETED: completeDelivery()
    COMPLETED --> [*]
}

state paymentapp {
    [*] --> P_SUBMITTED: createPayment()
    P_SUBMITTED --> P_APPROVED: approvePayment()
    P_APPROVED --> [*]
    P_APPROVED --> P_CANCELLED: cancelPayment()
    P_CANCELLED --> [*]
}

@enduml
